# $FreeBSD$

PORTNAME=	regex2dfa
DISTVERSION=	0.1.6
CATEGORIES=	textproc

MAINTAINER=	egypcio@googlemail.com
COMMENT=	Unofficial/experimental version of textproc/regex2dfa

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

GNU_CONFIGURE=	yes

USES=		gmake libtool

USE_GITHUB=	yes
GH_ACCOUNT=	kpdyer

.include <bsd.port.mk>
