# Created by: David Shane Holden <dpejesh@yahoo.com>
# $FreeBSD: head/net/corosync2/Makefile 518656 2019-11-29 14:42:31Z egypcio $

PORTVERSION=		2.4.5
PKGNAMESUFFIX=		2

.include "${.CURDIR}/Makefile.common"

CONFLICTS=		corosync3-[0-9]*

.include <bsd.port.mk>
