# Created by: Gea-Suan Lin <gslin@gslin.org>
# $FreeBSD: head/net/py-iplib/Makefile 486672 2018-12-05 14:09:12Z egypcio $

PORTNAME=	iplib
PORTVERSION=	1.2.1
CATEGORIES=	net python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	egypcio@FreeBSD.org
COMMENT=	Convert amongst many different IPv4 notations

LICENSE=	BSD3CLAUSE

USES=		python
USE_PYTHON=	autoplist distutils flavors

.include <bsd.port.mk>
