# $FreeBSD$

PORTNAME=		marionette
DISTVERSION=		0.1.0
DISTVERSIONPREFIX=	v
CATEGORIES=		security net python
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	egypcio@googlemail.com
COMMENT=	Programmable Network Traffic Obfuscation System

LICENSE=	APACHE20
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_GITHUB=	yes
USE_PYTHON=	flavors autoplist distutils

GH_ACCOUNT=	marionette-tg

.include <bsd.port.mk>
