# Created by: David Shane Holden <dpejesh@yahoo.com>
# $FreeBSD: head/devel/py-parallax/Makefile 532978 2020-04-25 20:43:53Z egypcio $

PORTNAME=		parallax
PORTVERSION=		1.0.6
CATEGORIES=		devel python
MASTER_SITES=		CHEESESHOP
PKGNAMEPREFIX=		${PYTHON_PKGNAMEPREFIX}

MAINTAINER=		egypcio@FreeBSD.org
COMMENT=		Python API for SSH

LICENSE=		BSD3CLAUSE
LICENSE_FILE=		${WRKSRC}/COPYING

USES=			python
USE_PYTHON=		distutils autoplist

.include <bsd.port.mk>
