# Created by: Mark Felder <feld@FreeBSD.org>
# $FreeBSD: head/devel/py-fabric3/Makefile 487674 2018-12-17 10:20:28Z egypcio $

PORTNAME=	fabric3
DISTVERSION=	1.14
DISTVERSIONSUFFIX=	.post1
CATEGORIES=	devel python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
DISTNAME=	Fabric3-${DISTVERSIONFULL}

MAINTAINER=	egypcio@FreeBSD.org
COMMENT=	Python tool for remote execution and deployment

LICENSE=	BSD3CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python
USE_PYTHON=	autoplist distutils

NO_ARCH=	yes

.include <bsd.port.mk>
