# $FreeBSD$

PORTNAME=	measurement-kit
DISTVERSION=	0.8.3
CATEGORIES=	net

MAINTAINER=	egypcio@googlemail.com
COMMENT=	Unofficial/experimental version of net/measurement-kit

LICENSE=	BSD2CLAUSE
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		cmake autoreconf
USE_LDCONFIG=	yes
USE_GITHUB=	yes
GH_TAGNAME=	v${DISTVERSION}

.include <bsd.port.mk>
