# $FreeBSD$

PORTNAME=	go-siphash
DISTVERSION=	g20170831
CATEGORIES=	security devel

MAINTAINER=	egypcio@googlemail.com
COMMENT=	Unofficial/experimental version of security/go-siphash

LICENSE=	CC0-1.0

USES=		go

USE_GITHUB=	yes

GH_ACCOUNT=	dchest
GH_PROJECT=	siphash
GH_TAGNAME=	4ebf1de

GO_PKGNAME=	github.com/${GH_ACCOUNT}/${GH_PROJECT}

.include <bsd.port.mk>
