# $FreeBSD$

PORTNAME=	centreon-plugins
PORTVERSION=	20170811
CATEGORIES=	net-mgmt
LICENSE=	AGPLv3
MAINTAINER=	egypcio@googlemail.com
COMMENT=	Unofficial/experimental version of net-mgmt/centreon-plugins

USE_GITHUB=	yes

GH_ACCOUNT=	centreon
GH_TAGNAME=	${PORTVERSION}

.include <bsd.port.mk>
