# $FreeBSD$

PORTNAME=		onionshare
DISTVERSION=		1.1
DISTVERSIONPREFIX=	v
CATEGORIES=		www security ipv6

MAINTAINER=	egypcio@googlemail.com
COMMENT=	Unofficial/experimental version of www/onionshare

LICENSE=	GPLv3
LICENSE_FILE=	${WRKSRC}/LICENSE

USES=		python

USE_GITHUB=	yes
USE_PYTHON=	distutils

GH_ACCOUNT=	micahflee

SUB_FILES=	pkg-message

.include <bsd.port.mk>
